"""Nova Vitral - component registry data.

One tuple per component: (kind, name, blurb).
`kind` selects the emitter in lib_emit.py; icons, props and file paths are derived
deterministically so the whole library stays consistent and regenerable.

26 categories, 500 components.
"""

# kind = emitter family. Categories are declared separately in CATEGORIES.
DATA = {
# ------------------------------------------------------------------ core (10)
"core": [
    ("surface", "surface", "Base glass surface with hairline edge and inner highlight."),
    ("surface", "surface-strong", "Elevated glass panel for modals, popovers and hero visuals."),
    ("surface", "inset", "Sunken panel for code, metadata and dense groups."),
    ("aurora", "aurora", "Fixed aurora background with three drifting blobs and grain."),
    ("aurora", "grain-overlay", "Noise layer that keeps large blurred areas from banding."),
    ("motion", "reveal", "IntersectionObserver reveal that fires once and respects reduced motion."),
    ("motion", "reveal-group", "Staggered container that animates children with a capped cascade."),
    ("section", "section", "Section wrapper with overline, title, lead and quiet-zone spacing."),
    ("section", "container", "Max-width container with responsive gutters."),
    ("divider", "divider", "Hairline divider with optional centered label."),
],
# ------------------------------------------------------------------ motion (24)
"motion": [
    ("motion", "counter", "Counts to a value once on view with tabular figures."),
    ("motion", "parallax-visual", "Scroll-linked vertical drift with spring damping."),
    ("motion", "parallax-layer", "Single depth layer for multi-layer parallax scenes."),
    ("motion", "scroll-progress", "Top progress bar driven by scroll ratio, GPU only."),
    ("motion", "scroll-linked-scale", "Scales a visual as it enters and leaves the viewport."),
    ("motion", "sticky-scrolly", "Sticky visual driven by a sequence of narrative steps."),
    ("motion", "horizontal-scroll", "Vertical scroll that drives a horizontal gallery."),
    ("motion", "marquee-row", "Infinite marquee with mask fade and hover pause."),
    ("motion", "tilt-card", "Capped 6 degree pointer tilt with spring return."),
    ("motion", "spotlight-card", "Pointer-following radial light on a glass surface."),
    ("motion", "magnetic-button", "Button that leans toward the pointer within limits."),
    ("motion", "text-reveal", "Word-by-word reveal for headlines."),
    ("motion", "blur-in", "Blur and fade entrance for media and images."),
    ("motion", "scale-in", "Scale entrance reserved for modals and featured cards."),
    ("motion", "fade-in", "Minimal opacity entrance for dense regions."),
    ("motion", "slide-in-x", "Horizontal entrance for drawers and side panels."),
    ("motion", "list-reorder", "Animated reordering for lists and queues."),
    ("motion", "layout-tabs", "Tabs whose indicator slides between items."),
    ("motion", "accordion-motion", "Height expansion via grid-template-rows, no JS measurement."),
    ("motion", "modal-motion", "Enter and exit animation pair for dialogs."),
    ("motion", "toast-motion", "Stacking enter and exit choreography for toasts."),
    ("motion", "page-transition", "180ms fade and rise between marketing routes."),
    ("motion", "typewriter", "Typed text with a caret, pauses on long stalls."),
    ("motion", "countdown-digits", "Launch countdown with digit swap, no bouncing."),
],
# ------------------------------------------------------------------ buttons (18)
"buttons": [
    ("button", "button-primary", "The single solid element: indigo gradient, glow on hover."),
    ("button", "button-glass", "Glass secondary action with hairline and blur."),
    ("button", "button-ghost", "Transparent until hover, for dense toolbars."),
    ("button", "button-outline", "Hairline outline that becomes accent on hover."),
    ("button", "button-danger", "Tinted destructive action, solid only in confirm dialogs."),
    ("button", "button-link", "Inline link styled as an action with underline offset."),
    ("button", "button-icon", "Icon-only button with label, tooltip and press scale."),
    ("button", "button-split", "Split action with a menu on the trailing segment."),
    ("button", "button-loading", "Loading state with locked width and inline spinner."),
    ("button", "button-success", "Success swap with a check and a 1.6s revert."),
    ("button", "button-group", "Segmented group sharing one glass shell."),
    ("button", "button-copy", "Copy action with check feedback, no toast."),
    ("button", "button-toggle", "Pressed state button for filters and toolbars."),
    ("button", "button-pill", "Pill action for chips rows and mobile filters."),
    ("button", "button-fab", "Floating action that appears after the first viewport."),
    ("button", "button-submit-bar", "Sticky submit bar with dirty-state enabling."),
    ("button", "button-async", "Async action with promise states and retry on failure."),
    ("button", "button-destructive-hold", "Hold-to-confirm for irreversible actions."),
],
# ------------------------------------------------------------------ inputs (24)
"inputs": [
    ("input", "input-text", "Text field with label, hint, error and icon slots."),
    ("input", "input-email", "Email field with domain validation and typo hints."),
    ("input", "input-password", "Password field with reveal toggle and strength meter."),
    ("input", "input-search", "Search field with debounce and clear action."),
    ("input", "input-textarea", "Auto-growing textarea capped at twelve rows."),
    ("input", "input-number", "Numeric field with steppers and tabular figures."),
    ("input", "input-currency", "Currency field with locale formatting and right alignment."),
    ("input", "input-phone", "Phone field that formats while typing and never blocks paste."),
    ("input", "input-otp", "Six-cell verification code with paste support."),
    ("input", "input-tags", "Tag entry with chip removal and keyboard commit."),
    ("input", "input-mention", "Mention field with grouped suggestion menu."),
    ("input", "input-prefix-suffix", "Field with locked prefix and unit suffix."),
    ("input", "switch", "Switch with 160ms thumb and aria role switch."),
    ("input", "checkbox", "Checkbox with indeterminate support."),
    ("input", "radio-card", "Radio rendered as a selectable tile with description."),
    ("input", "select", "Select with glass popup and check on the active row."),
    ("input", "combobox", "Searchable select with grouped results and empty state."),
    ("input", "multiselect", "Multi-select with chips, counts and clear-all."),
    ("input", "date-picker", "Calendar popover with presets and keyboard navigation."),
    ("input", "date-range", "Range picker with preset chips and dual month view."),
    ("input", "slider", "Slider with value bubble shown only while dragging."),
    ("input", "file-drop", "Dropzone with validation, per-file progress and retry."),
    ("input", "form-field", "Field shell that wires label, hint, error and aria-describedby."),
    ("input", "rating-input", "Star rating with keyboard support and hover preview."),
],
# ------------------------------------------------------------------ cards (26)
"cards": [
    ("card", "glass-card", "Default panel: glass, 24px radius, specular on hover."),
    ("card", "interactive-card", "Clickable card with lift, focus ring and pressed state."),
    ("card", "media-card", "Card with cover media, veil gradient and content footer."),
    ("card", "profile-card", "Person card with avatar, role, links and presence."),
    ("card", "product-card", "Product tile with price, badge and quick action."),
    ("card", "stat-card", "Metric with delta chip and comparison caption."),
    ("card", "metric-spark", "Metric with an inline 24-point sparkline."),
    ("card", "pricing-card", "Plan card with billing state, features and CTA."),
    ("card", "plan-compare-card", "Compact plan summary for comparison grids."),
    ("card", "testimonial-card", "Quote, attribution and logo slot."),
    ("card", "blog-card", "Article card with category chip and reading time."),
    ("card", "changelog-card", "Release entry with version chip and tags."),
    ("card", "repo-card", "Repository card with stars, language and update time."),
    ("card", "integration-card", "Integration tile with monochrome logo and status."),
    ("card", "team-card", "Team card with stacked avatars and member count."),
    ("card", "notification-card", "Notification with icon tone, action and dismiss."),
    ("card", "task-card", "Task with checkbox, assignee and due date."),
    ("card", "invoice-card", "Invoice summary with amount, status and download."),
    ("card", "usage-card", "Usage meter with quota and overage warning."),
    ("card", "seat-card", "Seat allocation with invite affordance."),
    ("card", "empty-card", "Empty state card with icon, copy and one action."),
    ("card", "error-card", "Block error with retry and copyable error id."),
    ("card", "skeleton-card", "Skeleton that mirrors a real card shape exactly."),
    ("card", "action-card", "Card whose whole surface is one decision."),
    ("card", "feature-card", "Feature with icon tile and two lines of copy."),
    ("card", "resource-card", "Link card for docs, guides and videos."),
],
# ------------------------------------------------------------------ navigation (26)
"navigation": [
    ("nav", "navbar", "Sticky navbar that condenses to glass after 24px."),
    ("nav", "navbar-links", "Nav links with sliding accent underline and scroll spy."),
    ("nav", "mega-menu", "Grouped menu with columns and a visual slot."),
    ("nav", "mobile-sheet-menu", "Off-canvas menu with 44px targets and focus trap."),
    ("nav", "sidebar", "App sidebar with sections and persisted collapse."),
    ("nav", "sidebar-rail", "Icon rail with delayed tooltips."),
    ("nav", "sidebar-item", "Nav item with active bar, badge and focus states."),
    ("nav", "breadcrumbs", "Breadcrumbs that collapse beyond four levels."),
    ("nav", "tabs", "Tabs with keyboard navigation and lazy panels."),
    ("nav", "tabs-underline", "Underline tabs for content sections."),
    ("nav", "tabs-segmented", "Segmented control for view switching."),
    ("nav", "pagination", "Pagination with window compression and page size."),
    ("nav", "stepper", "Horizontal stepper for multi-step flows."),
    ("nav", "wizard-progress", "Vertical progress for onboarding wizards."),
    ("nav", "command-palette", "Cmd K palette with scopes, recents and shortcut hints."),
    ("nav", "dock", "Floating glass dock for primary app actions."),
    ("nav", "floating-nav", "Compact nav that appears on scroll up."),
    ("nav", "anchors-toc", "On-this-page rail with active marker."),
    ("nav", "back-to-top", "Appears after 1.5 viewports with smooth scroll."),
    ("nav", "scroll-spy-nav", "Sections tracked by IntersectionObserver."),
    ("nav", "footer", "Footer with link columns, status pill and legal bar."),
    ("nav", "footer-oversized", "Footer with an oversized clipped wordmark."),
    ("nav", "user-menu", "Account menu with theme control and sign out."),
    ("nav", "org-switcher", "Workspace switcher with search and creation."),
    ("nav", "keyboard-hints", "Shortcut reference chips for the current view."),
    ("nav", "sub-nav", "Secondary nav for nested product areas."),
],
# ------------------------------------------------------------------ data (30)
"data": [
    ("table", "data-table", "Table with sticky header, hover rows and actions."),
    ("table", "table-selectable", "Row selection with tri-state header checkbox."),
    ("table", "table-virtualized", "Virtualized table for ten thousand rows."),
    ("table", "table-expandable", "Rows that expand into a detail panel."),
    ("table", "table-sortable", "Sortable columns with three-state cycling."),
    ("table", "table-pinned", "First column pinned with a scroll fade mask."),
    ("table", "table-pagination", "Pagination with page size and range summary."),
    ("table", "table-toolbar", "Toolbar with search, filters and column control."),
    ("table", "table-bulk-bar", "Bulk action bar for a selection."),
    ("table", "columns-manager", "Column visibility and order manager."),
    ("data", "filter-bar", "Active filter chips with counts and clear-all."),
    ("data", "filter-panel", "Filter rail with groups, ranges and counts."),
    ("data", "saved-views", "Saved views as segmented chips with pinning."),
    ("data", "sparkline", "24-point inline sparkline with gradient fill."),
    ("data", "area-chart", "Area chart with gradient fill and reference line."),
    ("data", "bar-chart", "Sorted horizontal bars with direct labels."),
    ("data", "stacked-bar", "Stacked bars for composition over time."),
    ("data", "donut-chart", "Donut limited to three slices with a center total."),
    ("data", "heatmap", "Day and hour activity heatmap."),
    ("data", "funnel-chart", "Funnel with step conversion percentages."),
    ("data", "bullet-chart", "Progress against a target with a marker."),
    ("data", "scatter-plot", "Scatter with trend line and hover tooltip."),
    ("data", "gauge", "Radial gauge for a single bounded metric."),
    ("data", "progress-bar", "Progress with label and percentage."),
    ("data", "progress-ring", "Circular progress for compact spaces."),
    ("data", "stat-compare", "Two metrics compared with direction emphasis."),
    ("data", "delta-chip", "Up or down chip with inverted-good support."),
    ("data", "chart-legend", "Legend that toggles series visibility."),
    ("data", "chart-tooltip", "Glass tooltip with series dot and tabular values."),
    ("data", "chart-empty", "Empty chart with axes, grid and a centered hint."),
],
# ------------------------------------------------------------------ chat (30)
"chat": [
    ("chat", "chat-shell", "Three-region layout with independent scroll containers."),
    ("chat", "thread", "Message list with grouping, day separators and live region."),
    ("chat", "message-user", "Right-aligned glass bubble with hover actions."),
    ("chat", "message-assistant", "Full-width markdown answer with identity row."),
    ("chat", "message-system", "Centered notice chip on a hairline."),
    ("chat", "reasoning-drawer", "Collapsed thought summary with duration chip."),
    ("chat", "thinking-row", "Dots, shimmer label and the latency ladder."),
    ("chat", "tool-card", "Tool call with state rule, parameters and result."),
    ("chat", "tool-approval", "Approval card for write, spend and delete actions."),
    ("chat", "artifact-card", "Preview strip, version chip and open canvas."),
    ("chat", "canvas-panel", "Split panel with preview, code and versions."),
    ("chat", "composer", "Sticky glass composer with auto-grow textarea."),
    ("chat", "composer-tools", "Model, tools and attachment controls."),
    ("chat", "slash-menu", "Command menu anchored above the composer."),
    ("chat", "mention-menu", "Mention menu for files, people and tools."),
    ("chat", "attachment-chip", "File chip with upload ring and remove."),
    ("chat", "attachment-grid", "Image attachment grid with lightbox."),
    ("chat", "streaming-caret", "Caret that never jumps backward and pauses on stalls."),
    ("chat", "message-actions", "Copy, regenerate, rate, branch and share."),
    ("chat", "message-rating", "Inline feedback card with category chips."),
    ("chat", "citation", "Superscript reference with a hover preview card."),
    ("chat", "sources-row", "Numbered source list with show-all expansion."),
    ("chat", "follow-ups", "Post-answer suggestion chips that send directly."),
    ("chat", "suggestion-grid", "Empty-state prompt tiles that fill the composer."),
    ("chat", "session-rail", "Conversation history with search, pin and bulk actions."),
    ("chat", "session-item", "History row with rename, pin and delete."),
    ("chat", "context-panel", "Artifacts, sources, memory and token budget."),
    ("chat", "token-meter", "Context usage with a bar and reset countdown."),
    ("chat", "model-picker", "Grouped model list with context and cost hints."),
    ("chat", "typing-presence", "Collaborator typing indicator and avatar stack."),
],
# ------------------------------------------------------------------ overlays (22)
"overlays": [
    ("overlay", "modal", "Centered dialog with scrim, focus trap and exit."),
    ("overlay", "confirm-dialog", "Confirmation with danger action and typed phrase."),
    ("overlay", "drawer-right", "Right drawer for forms and details."),
    ("overlay", "sheet-bottom", "Bottom sheet for mobile actions and filters."),
    ("overlay", "popover", "Anchored glass popover with collision handling."),
    ("overlay", "tooltip", "Delayed tooltip limited to a label."),
    ("overlay", "dropdown-menu", "Menu with shortcuts, groups and danger row."),
    ("overlay", "context-menu", "Right-click menu sharing the menu primitive."),
    ("overlay", "hover-card", "Rich preview on hover with delay."),
    ("overlay", "lightbox", "Media viewer with keyboard, swipe and preloading."),
    ("overlay", "side-panel", "Persistent side panel for inspection."),
    ("overlay", "inspector", "Property inspector for a selected object."),
    ("overlay", "quick-edit", "Inline edit surface that replaces content."),
    ("overlay", "onboarding-tour", "Coach marks with a spotlight cutout."),
    ("overlay", "announce-bar", "Top announcement with dismiss memory."),
    ("overlay", "cookie-bar", "Non-blocking consent with two real choices."),
    ("overlay", "toaster", "Toast host with stacking and promise support."),
    ("overlay", "toast-item", "Single toast with icon tone and action."),
    ("overlay", "banner-inline", "Inline notice with a fix action."),
    ("overlay", "slide-over-form", "Slide-over wrapping a full form."),
    ("overlay", "command-sheet", "Mobile command surface."),
    ("overlay", "preview-modal", "Preview of a file or artifact before commit."),
],
# ------------------------------------------------------------------ feedback (20)
"feedback": [
    ("feedback", "skeleton-text", "Text skeleton with three line widths."),
    ("feedback", "skeleton-card", "Card skeleton matching the real shape."),
    ("feedback", "skeleton-table", "Table skeleton with five rows and a header."),
    ("feedback", "skeleton-chart", "Chart skeleton with a ghost of the previous chart."),
    ("feedback", "empty-state", "Icon tile, one explanation and one action."),
    ("feedback", "empty-search", "Zero results with removable filters."),
    ("feedback", "error-state", "Plain-language error with retry and error id."),
    ("feedback", "error-boundary-card", "Boundary fallback scoped to one region."),
    ("feedback", "offline-banner", "Amber offline notice with queued count."),
    ("feedback", "rate-limit-notice", "Limit reached with a countdown and upgrade path."),
    ("feedback", "loading-dots", "Three dots for short waits."),
    ("feedback", "loading-bar", "Indeterminate bar for long operations."),
    ("feedback", "spinner", "Spinner with an accessible label."),
    ("feedback", "progress-ring", "Ring progress with a center value."),
    ("feedback", "pulse-dot", "Live indicator, one per viewport."),
    ("feedback", "status-pill", "Operational, degraded or outage status."),
    ("feedback", "badge-status", "Status chip with tone and dot."),
    ("feedback", "alert-info", "Informational callout."),
    ("feedback", "alert-warning", "Warning callout with a fix."),
    ("feedback", "alert-danger", "Error callout with retry."),
],
# ------------------------------------------------------------------ marketing (40)
"marketing": [
    ("marketing", "hero-centered", "Centered hero with gradient headline and visual anchor."),
    ("marketing", "hero-split", "Split hero with copy and product panel."),
    ("marketing", "hero-chat", "Hero whose visual is a working chat exchange."),
    ("marketing", "hero-minimal", "Type-first hero without a visual."),
    ("marketing", "announcement-pill", "Release pill with a live dot and arrow."),
    ("marketing", "logo-cloud", "Monochrome logo row at reduced opacity."),
    ("marketing", "marquee-logos", "Infinite logo marquee with mask fade."),
    ("marketing", "features-bento", "Bento grid with one hero cell."),
    ("marketing", "features-grid", "Three-column feature grid with icon tiles."),
    ("marketing", "features-alternating", "Alternating rows of copy and visual."),
    ("marketing", "feature-list-icons", "Compact checklist of capabilities."),
    ("marketing", "stats-band", "Four animated metrics with context captions."),
    ("marketing", "process-steps", "Numbered steps with a filling connector."),
    ("marketing", "how-it-works", "Three-step explainer with a tabbed preview."),
    ("marketing", "testimonials-grid", "Three quote cards with real attribution."),
    ("marketing", "testimonial-wall", "Two columns with a 0.04 parallax offset."),
    ("marketing", "testimonial-featured", "Portrait plus quote at half width each."),
    ("marketing", "integrations-grid", "Integration tiles with hover names."),
    ("marketing", "comparison-table", "Honest feature comparison with an accent column."),
    ("marketing", "pricing-three", "Three plans with a billing toggle."),
    ("marketing", "pricing-toggle", "Monthly and annual segmented control."),
    ("marketing", "pricing-comparison", "Full feature matrix with sticky header."),
    ("marketing", "pricing-calculator", "Live estimate from sliders and inputs."),
    ("marketing", "faq-accordion", "Single-open accordion with deep links."),
    ("marketing", "faq-two-column", "Questions left, answers right."),
    ("marketing", "cta-band", "Full-width glass band with an internal glow."),
    ("marketing", "cta-split", "CTA with a metric on the trailing side."),
    ("marketing", "newsletter-inline", "Inline capture with success replacement."),
    ("marketing", "waitlist", "Email capture with position and referral."),
    ("marketing", "roadmap", "Now, next and later columns."),
    ("marketing", "changelog-list", "Timeline of releases with tags."),
    ("marketing", "security-badges", "Compliance badge grid with a trust link."),
    ("marketing", "team-grid", "Team members with roles and socials."),
    ("marketing", "careers-list", "Open roles with location and team chips."),
    ("marketing", "customers-grid", "Customer logos with case study links."),
    ("marketing", "case-study-band", "One metric, one sentence, one logo."),
    ("marketing", "metrics-row", "Compact metric strip for the mid page."),
    ("marketing", "trust-row", "Avatars, rating and volume claim."),
    ("marketing", "closing-cta", "Final conversion block with micro-copy."),
    ("marketing", "product-tour", "Tabbed interface preview with fixed aspect."),
],
# ------------------------------------------------------------------ shell (18)
"shell": [
    ("shell", "app-layout", "Sidebar, topbar and content shell."),
    ("shell", "topbar", "App topbar with breadcrumb and actions."),
    ("shell", "workspace-switcher", "Workspace menu with search and create."),
    ("shell", "notification-bell", "Bell with unread count and popover list."),
    ("shell", "activity-drawer", "Right drawer with recent workspace events."),
    ("shell", "settings-layout", "Settings rail plus content column."),
    ("shell", "settings-section", "Section with autosave and dirty tracking."),
    ("shell", "settings-rail", "Section navigation for settings."),
    ("shell", "danger-zone", "Destructive section with typed confirmation."),
    ("shell", "api-keys-table", "Key table with masked reveal and revoke."),
    ("shell", "sessions-table", "Active sessions with revoke actions."),
    ("shell", "billing-panel", "Plan, seats, payment method and invoices."),
    ("shell", "usage-meter", "Quota usage with overage projection."),
    ("shell", "members-table", "Members with roles and last active."),
    ("shell", "invite-dialog", "Invite by email with role select."),
    ("shell", "role-select", "Role picker with permission summary."),
    ("shell", "audit-log", "Authored timeline of workspace actions."),
    ("shell", "profile-form", "Profile details with avatar upload."),
],
# ------------------------------------------------------------------ ai (20)
"ai": [
    ("ai", "prompt-library", "Saved prompts with tags and insert action."),
    ("ai", "persona-card", "System persona with tone and constraints."),
    ("ai", "prompt-variable-form", "Fills template variables before sending."),
    ("ai", "model-select", "Model picker with capability hints."),
    ("ai", "temperature-control", "Creativity control with three labelled stops."),
    ("ai", "tool-toggle-list", "Enable or disable agent tools."),
    ("ai", "agent-step-list", "Plan steps with status and duration."),
    ("ai", "agent-run-card", "A single agent run with outcome and cost."),
    ("ai", "agent-log-stream", "Streaming log with level filters."),
    ("ai", "eval-table", "Evaluation results with pass rates."),
    ("ai", "dataset-card", "Dataset summary with row count and schema."),
    ("ai", "embed-badge", "Embedding model badge with dimension."),
    ("ai", "rag-source-list", "Retrieved chunks with scores."),
    ("ai", "memory-card", "Long-term memory entries the agent can use."),
    ("ai", "guardrail-panel", "Policy rules with severity and action."),
    ("ai", "cost-panel", "Spend by model, tokens and period."),
    ("ai", "token-budget", "Context budget with trimming advice."),
    ("ai", "latency-badge", "Latency and throughput indicator."),
    ("ai", "streaming-status", "Connection health for a live stream."),
    ("ai", "insight-card", "Generated insight with confidence and sources."),
],
# ------------------------------------------------------------------ editors (14)
"editors": [
    ("editor", "code-block", "Code with language chip, copy and wrap toggle."),
    ("editor", "code-tabs", "Multi-language tabbed code samples."),
    ("editor", "terminal", "Framed terminal with typed command option."),
    ("editor", "diff-viewer", "Unified diff with hunk collapse."),
    ("editor", "json-tree", "Collapsible JSON with copy-path actions."),
    ("editor", "markdown-preview", "Rendered markdown with a raw toggle."),
    ("editor", "rich-text-toolbar", "Formatting toolbar for authoring surfaces."),
    ("editor", "slash-editor", "Block editor with slash commands."),
    ("editor", "cell-editor", "Spreadsheet-style cell editing."),
    ("editor", "formula-input", "Formula field with function hints."),
    ("editor", "canvas-board", "Freeform board for diagrams and notes."),
    ("editor", "sticky-note", "Small note surface with colour tones."),
    ("editor", "comment-thread", "Threaded comments with resolve."),
    ("editor", "mention-input", "Inline mention authoring with a menu."),
],
# ------------------------------------------------------------------ media (16)
"media": [
    ("media", "image-card", "Image with caption, hairline frame and lightbox."),
    ("media", "gallery-grid", "Responsive media grid with selection."),
    ("media", "lightbox-thumbs", "Thumbnail strip synced with a viewer."),
    ("media", "video-player", "Glass chrome, poster veil and captions."),
    ("media", "audio-waveform", "Waveform player with speed control."),
    ("media", "avatar", "Avatar with initials fallback on a calm gradient."),
    ("media", "avatar-group", "Overlapping avatars with an overflow chip."),
    ("media", "avatar-upload", "Upload with crop framing and remove."),
    ("media", "logo-tile", "Monochrome logo tile that saturates on hover."),
    ("media", "favicon-chip", "Domain chip with favicon and title."),
    ("media", "icon-tile", "Feature icon inside a 40px glass tile."),
    ("media", "illustration-frame", "Glass plate framing an illustration."),
    ("media", "device-frame", "Laptop or phone frame for screenshots."),
    ("media", "screenshot-frame", "Browser chrome frame for product shots."),
    ("media", "before-after", "Comparison of two states with a divider."),
    ("media", "file-preview", "Preview sheet for a document or image file."),
],
# ------------------------------------------------------------------ commerce (16)
"commerce": [
    ("commerce", "product-tile", "Product with price, plan chip and CTA."),
    ("commerce", "cart-line", "Cart row with quantity and remove."),
    ("commerce", "checkout-summary", "Totals with tax lines and discount."),
    ("commerce", "coupon-input", "Coupon field with inline validation."),
    ("commerce", "invoice-row", "Invoice line with status and amount."),
    ("commerce", "seat-picker", "Seat quantity with volume pricing hint."),
    ("commerce", "plan-switcher", "Change plan with proration preview."),
    ("commerce", "usage-based-meter", "Metered billing with alert thresholds."),
    ("commerce", "trial-banner", "Trial countdown with an upgrade action."),
    ("commerce", "upgrade-prompt", "Contextual upgrade at the limit."),
    ("commerce", "discount-chip", "Savings chip with original price."),
    ("commerce", "price-display", "Price with period and billing note."),
    ("commerce", "payment-method-card", "Saved card with expiry and default marker."),
    ("commerce", "receipt-card", "Payment receipt with a download action."),
    ("commerce", "refund-panel", "Refund request with reason and amount."),
    ("commerce", "billing-toggle", "Monthly and annual switch with savings note."),
],
# ------------------------------------------------------------------ forms (18)
"forms": [
    ("form", "multi-step-form", "Stepped form with validation per step."),
    ("form", "form-section", "Grouped fields with a section heading."),
    ("form", "form-summary", "Error summary that links to each field."),
    ("form", "field-group", "Label, hint and error wiring wrapper."),
    ("form", "address-form", "Address fields with postal lookup hints."),
    ("form", "card-form", "Payment details with formatting masks."),
    ("form", "credit-card-input", "Card number, expiry and CVC in one row."),
    ("form", "signature-pad", "Canvas signature with clear and undo."),
    ("form", "survey-scale", "Likert scale with accessible radio semantics."),
    ("form", "upload-list", "Upload progress list with retry."),
    ("form", "dynamic-list-form", "Repeatable rows with add and remove."),
    ("form", "validation-summary", "Top-of-form summary after a failed submit."),
    ("form", "async-validation", "Debounced server-side field validation."),
    ("form", "draft-banner", "Restored draft notice with discard."),
    ("form", "unsaved-guard", "Blocks navigation when the form is dirty."),
    ("form", "submit-bar", "Sticky bar with dirty enabling and cancel."),
    ("form", "conditional-fields", "Fields revealed by a previous answer."),
    ("form", "autosave-indicator", "Saved state without layout shift."),
],
# ------------------------------------------------------------------ layout (20)
"layout": [
    ("layout", "bento-grid", "Mixed spans with one hero cell."),
    ("layout", "split-layout", "Two-column split with a sticky side."),
    ("layout", "sticky-aside", "Sticky sidebar that releases before the next section."),
    ("layout", "two-column-prose", "Measure-capped article layout."),
    ("layout", "docs-layout", "Tree, content and on-this-page rail."),
    ("layout", "blog-layout", "Index with featured post and grid."),
    ("layout", "portfolio-grid", "Project grid with mixed media."),
    ("layout", "masonry", "Column-based masonry for uneven media."),
    ("layout", "gallery-mosaic", "Mosaic gallery with a full-bleed row."),
    ("layout", "sidebar-content", "App shell with a collapsible sidebar."),
    ("layout", "full-bleed", "Edge-to-edge band inside a contained page."),
    ("layout", "section-header", "Overline, title, lead and action."),
    ("layout", "page-header", "Page title with breadcrumb and actions."),
    ("layout", "content-header", "Content header with meta row."),
    ("layout", "article-header", "Article header with author and date."),
    ("layout", "sticky-toolbar", "Toolbar that sticks under the navbar."),
    ("layout", "action-bar", "Contextual actions for a selection."),
    ("layout", "stats-header", "Header with inline metrics."),
    ("layout", "hero-content", "Content-first hero for inner pages."),
    ("layout", "empty-layout", "Centered single-column layout for states."),
],
# ------------------------------------------------------------------ devtools (14)
"devtools": [
    ("devtool", "command-bar", "Inline command input with suggestions."),
    ("devtool", "hotkey-list", "Catalog of keyboard shortcuts."),
    ("devtool", "feature-flag-panel", "Flags with rollout percentage."),
    ("devtool", "env-switcher", "Environment switch with a danger tone."),
    ("devtool", "log-viewer", "Log stream with level filter and tail."),
    ("devtool", "json-inspector", "Property inspector for a payload."),
    ("devtool", "request-timeline", "Waterfall of requests and durations."),
    ("devtool", "network-table", "Network calls with status and size."),
    ("devtool", "perf-meter", "Frame budget and long task counter."),
    ("devtool", "error-report", "Crash report with stack and context."),
    ("devtool", "debug-drawer", "Bottom drawer with runtime state."),
    ("devtool", "api-playground", "Request builder with response viewer."),
    ("devtool", "webhook-tester", "Endpoint tester with event replay."),
    ("devtool", "schema-viewer", "Table schema with column types."),
],
# ------------------------------------------------------------------ utilities (18)
"utilities": [
    ("utility", "copy-button", "Copy with check feedback and no toast."),
    ("utility", "tooltip-label", "Label plus delayed tooltip."),
    ("utility", "keyboard-chip", "Key cap chip, desktop only."),
    ("utility", "relative-time", "Relative time with absolute on hover."),
    ("utility", "number-format", "Locale-aware number with compact notation."),
    ("utility", "currency-text", "Currency with tabular figures."),
    ("utility", "truncate-text", "Single-line ellipsis with title attribute."),
    ("utility", "middle-truncate", "Middle truncation for paths and keys."),
    ("utility", "password-strength", "Strength meter with requirement list."),
    ("utility", "qr-card", "Shareable QR with a download action."),
    ("utility", "share-row", "Share targets with a copyable link."),
    ("utility", "print-button", "Print with stylesheet guidance."),
    ("utility", "theme-toggle", "System, light and dark segmented control."),
    ("utility", "locale-switcher", "Language selector with persistence."),
    ("utility", "timezone-select", "Timezone picker with offsets."),
    ("utility", "currency-select", "Currency picker with symbols."),
    ("utility", "contrast-checker", "Reports contrast of two tokens."),
    ("utility", "token-preview", "Shows a token name, value and swatch."),
],
# ------------------------------------------------------------------ mobile (16)
"mobile": [
    ("mobile", "bottom-nav", "Four-item bottom navigation with a safe area."),
    ("mobile", "tab-bar", "Scrollable tab bar for mobile filters."),
    ("mobile", "swipe-card", "Card with swipe actions on touch."),
    ("mobile", "pull-to-refresh", "Refresh indicator driven by drag."),
    ("mobile", "action-sheet", "Sheet with grouped actions and cancel."),
    ("mobile", "mobile-nav-header", "Compact header with back and actions."),
    ("mobile", "sticky-cta", "Sticky bottom CTA with safe-area padding."),
    ("mobile", "list-row", "Touch row with avatar, meta and chevron."),
    ("mobile", "list-group", "Grouped list with a section header."),
    ("mobile", "swipe-actions", "Reveal actions behind a row."),
    ("mobile", "mobile-search", "Full-screen search with recents."),
    ("mobile", "bottom-sheet-form", "Form inside a bottom sheet."),
    ("mobile", "segmented-mobile", "Two-way segmented switch for small screens."),
    ("mobile", "floating-action", "Primary action pinned above the bottom nav."),
    ("mobile", "drawer-handle", "Drag handle with a collapsed state."),
    ("mobile", "safe-area-spacer", "Respects home indicator spacing."),
],
# ------------------------------------------------------------------ email (12)
"email": [
    ("email", "email-layout", "600px single column with dark panels."),
    ("email", "email-hero", "Subject, preheader and one primary action."),
    ("email", "email-cta", "Bulletproof button with a fallback link."),
    ("email", "email-receipt", "Payment receipt with a line item table."),
    ("email", "email-digest", "Weekly digest with five entries."),
    ("email", "email-invite", "Workspace invite with role and expiry."),
    ("email", "email-verify", "Verification with a code and a link."),
    ("email", "email-reset", "Password reset with a short expiry warning."),
    ("email", "email-changelog", "Release notes with category tags."),
    ("email", "email-footer", "Preference and unsubscribe links."),
    ("email", "email-quote", "Testimonial block for campaign mail."),
    ("email", "email-signature", "Sender identity block."),
],
# ------------------------------------------------------------------ print (8)
"print": [
    ("print", "print-header", "Document header with logo and reference."),
    ("print", "print-invoice", "Printable invoice with totals and terms."),
    ("print", "print-report", "Report cover with period and author."),
    ("print", "print-cover", "Cover page with title and metadata."),
    ("print", "print-table", "Table that repeats its header across pages."),
    ("print", "print-chart", "Chart with a caption that survives grayscale."),
    ("print", "print-signature", "Signature block with date line."),
    ("print", "print-footer", "Page number and confidentiality note."),
],
# ------------------------------------------------------------------ seo (10)
"seo": [
    ("seo", "metadata-card", "Title, description and canonical summary."),
    ("seo", "og-preview", "Open Graph image preview at 1200x630."),
    ("seo", "twitter-preview", "Card preview for social sharing."),
    ("seo", "structured-data-card", "JSON-LD summary with validation state."),
    ("seo", "sitemap-row", "Sitemap entry with lastmod and priority."),
    ("seo", "robots-panel", "Robots directives with a diff view."),
    ("seo", "canonical-chip", "Canonical URL chip with copy."),
    ("seo", "hreflang-list", "Locale alternates with validation."),
    ("seo", "reading-progress", "Scroll progress for long articles."),
    ("seo", "share-preview", "Preview of a shared link unfurl."),
],
# ------------------------------------------------------------------ a11y (10)
"a11y": [
    ("a11y", "skip-link", "First focusable element that jumps to main."),
    ("a11y", "live-region", "Polite or assertive announcements for async work."),
    ("a11y", "focus-trap-wrapper", "Keeps focus inside overlays."),
    ("a11y", "keyboard-nav-list", "List navigable with arrows and typeahead."),
    ("a11y", "described-by-hint", "Wires hint and error ids to a field."),
    ("a11y", "reduced-motion-guard", "Renders the final state without motion."),
    ("a11y", "landmark-region", "Named landmark wrapper for sections."),
    ("a11y", "accessible-icon-button", "Icon button with a guaranteed label."),
    ("a11y", "sr-summary", "Screen-reader summary for dense widgets."),
    ("a11y", "contrast-safe-badge", "Badge that picks a readable foreground."),
],
# ------------------------------------------------------------------ enterprise (20)
"enterprise": [
    ("enterprise", "sso-config", "SAML or OIDC setup with test connection."),
    ("enterprise", "scim-table", "Provisioned users with sync state."),
    ("enterprise", "rbac-matrix", "Role and permission grid."),
    ("enterprise", "permission-chip", "Single permission with a scope tooltip."),
    ("enterprise", "role-card", "Role with member count and description."),
    ("enterprise", "team-switcher", "Team context switch."),
    ("enterprise", "org-card", "Organization identity and plan."),
    ("enterprise", "audit-timeline", "Immutable action history."),
    ("enterprise", "compliance-badge", "SOC 2, GDPR or HIPAA badge."),
    ("enterprise", "data-residency-select", "Region selection with latency note."),
    ("enterprise", "sla-card", "Uptime commitment and credits."),
    ("enterprise", "security-review-card", "Questionnaire progress for procurement."),
    ("enterprise", "contract-card", "Term, renewal and signed documents."),
    ("enterprise", "procurement-checklist", "Vendor onboarding steps."),
    ("enterprise", "enterprise-cta", "Talk to sales with real assurances."),
    ("enterprise", "sales-contact", "Named contact with response time."),
    ("enterprise", "onboarding-checklist", "Five-step workspace setup."),
    ("enterprise", "migration-panel", "Import from a competitor with mapping."),
    ("enterprise", "sandbox-banner", "Sandbox environment warning."),
    ("enterprise", "trust-center-row", "Trust center entry with document links."),
],
}

CATEGORIES = [
    ("core", "Core primitives: surfaces, aurora, reveal, section and layout atoms."),
    ("motion", "Motion primitives: scroll, parallax, counters, tilt, marquees, transitions."),
    ("buttons", "Every action shape, from primary to hold-to-confirm."),
    ("inputs", "Form controls with labels, hints, errors and keyboard support."),
    ("cards", "Surfaces for metrics, people, media, tasks and money."),
    ("navigation", "Navbars, sidebars, tabs, palettes, pagination and footers."),
    ("data", "Tables, filters, charts and progress indicators."),
    ("chat", "The complete conversational surface: thread, streaming, tools, composer."),
    ("overlays", "Dialogs, drawers, popovers, menus, tours and toasts."),
    ("feedback", "Skeletons, empty states, errors, alerts and status."),
    ("marketing", "Page sections: heroes, features, pricing, proof, FAQ and CTAs."),
    ("shell", "Application shell and settings surfaces."),
    ("ai", "Agent tooling: prompts, models, runs, evaluations, cost and guardrails."),
    ("editors", "Code, diff, JSON, markdown and authoring surfaces."),
    ("media", "Images, video, audio, avatars, logos and frames."),
    ("commerce", "Product, cart, checkout, invoices and billing meters."),
    ("forms", "Multi-step and advanced form patterns."),
    ("layout", "Structural layouts and page-level compositions."),
    ("devtools", "Developer surfaces: logs, network, schema and debugging."),
    ("utilities", "Micro utilities: copy, time, numbers, theme and locale."),
    ("mobile", "Mobile-native patterns with safe areas and gestures."),
    ("email", "Email-safe components without backdrop blur."),
    ("print", "Print and PDF components."),
    ("seo", "Technical SEO and sharing previews."),
    ("a11y", "Accessibility primitives that ship with every page."),
    ("enterprise", "Enterprise administration, trust and procurement."),
]

def total() -> int:
    return sum(len(v) for v in DATA.values())

if __name__ == "__main__":
    n = total()
    print(f"{len(DATA)} categories, {n} components")
    for cat, _ in CATEGORIES:
        print(f"  {cat:12} {len(DATA[cat]):>3}")
