"""Per-kind page data: props table, motion contract, ASCII preview and usage example.

One entry per `kind` in scripts/lib_data.py. Every generated component page shares the
same signature discipline (title, subtitle, className plus kind-specific props), so a
single example and a single props table per kind stay truthful for all of its members.
"""

# (prop, type, default, notes)
PROPS: dict[str, list[tuple[str, str, str, str]]] = {
    "surface": [
        ("strong", "boolean", "false", "Elevated fill, larger blur, deeper shadow."),
        ("inset", "boolean", "false", "Sunken variant for nested regions."),
        ("padding", '"none" | "sm" | "md" | "lg"', '"md"', "Spacing from the token scale."),
        ("className", "string", "-", "Merged last, so call sites win."),
    ],
    "aurora": [
        ("intensity", "number", "1", "0 to 1.5, dims the whole layer."),
        ("angle", "number", "0", "Rotates the blob layout in degrees."),
        ("className", "string", "-", "Merged last."),
    ],
    "motion": [
        ("delay", "number", "0", "Milliseconds, capped at 400 by the cascade rule."),
        ("distance", "number", "16", "Travel in pixels; 8 for chips, 24 for panels."),
        ("as", "ElementType", '"div"', "Rendered element."),
        ("className", "string", "-", "Merged last."),
    ],
    "section": [
        ("title", "ReactNode", "-", "Section heading, rendered at --fs-h2."),
        ("subtitle", "ReactNode", "-", "One sentence under the heading, muted."),
        ("density", '"default" | "dense"', '"default"', "96 to 128px rhythm, or 48 to 64px."),
        ("className", "string", "-", "Merged last."),
    ],
    "divider": [
        ("label", "string", "-", "Optional centered overline."),
        ("spacing", '"sm" | "md" | "lg"', '"md"', "Vertical space around the rule."),
        ("className", "string", "-", "Merged last."),
    ],
    "card": [
        ("title", "string", "-", "Card heading, 16px semibold."),
        ("subtitle", "string", "-", "One supporting line, muted."),
        ("interactive", "boolean", "false", "Adds hover lift and the entrance reveal."),
        ("className", "string", "-", "Merged last."),
    ],
    "button": [
        ("title", "string", "-", "Button label."),
        ("iconLeft", "ReactNode", "-", "Lucide icon at 16px."),
        ("iconRight", "ReactNode", "-", "Trailing icon, often ArrowRight."),
        ("disabled", "boolean", "false", "Blocks interaction and drops opacity to 45 percent."),
    ],
    "input": [
        ("title", "string", "-", "Label text, linked with htmlFor."),
        ("subtitle", "string", "-", "Helper text under the field."),
        ("error", "string", "-", "Error message; also sets aria-invalid."),
        ("className", "string", "-", "Merged last."),
    ],
    "nav": [
        ("title", "string", "-", "Brand or breadcrumb label."),
        ("subtitle", "string", "-", "Secondary line, muted."),
        ("current", "string", "-", "Marks the active route."),
        ("className", "string", "-", "Merged last."),
    ],
    "data": [
        ("title", "string", "-", "Chart heading."),
        ("subtitle", "string", "-", "Period or unit, muted."),
        ("values", "number[]", "[]", "Series values; the default renders a sample."),
        ("className", "string", "-", "Merged last."),
    ],
    "table": [
        ("title", "string", "-", "Table caption."),
        ("subtitle", "string", "-", "Result count or scope, muted."),
        ("pageSize", "number", "10", "Rows per page."),
        ("className", "string", "-", "Merged last."),
    ],
    "chat": [
        ("title", "string", "-", "Turn heading, rarely visible."),
        ("subtitle", "string", "-", "Timestamp or model line."),
        ("streaming", "boolean", "false", "Keeps the caret and the stop control."),
        ("className", "string", "-", "Merged last."),
    ],
    "overlay": [
        ("title", "string", "-", "Dialog or sheet heading."),
        ("subtitle", "string", "-", "Supporting sentence, muted."),
        ("open", "boolean", "false", "Controlled visibility."),
        ("className", "string", "-", "Merged last."),
    ],
    "feedback": [
        ("title", "string", "-", "State headline."),
        ("subtitle", "string", "-", "One explanation, no exclamation marks."),
        ("tone", '"info" | "warn" | "danger"', '"info"', "Maps to the semantic tokens."),
        ("className", "string", "-", "Merged last."),
    ],
    "marketing": [
        ("title", "string", "-", "Headline; the hero uses --fs-display."),
        ("subtitle", "string", "-", "Lead paragraph, max 62 characters per line."),
        ("action", "ReactNode", "-", "One primary action, plus at most one secondary."),
        ("className", "string", "-", "Merged last."),
    ],
    "shell": [
        ("title", "string", "-", "Product name in the shell."),
        ("subtitle", "string", "-", "Workspace or tenant name."),
        ("collapsed", "boolean", "false", "Icon rail instead of the full sidebar."),
        ("className", "string", "-", "Merged last."),
    ],
    "ai": [
        ("title", "string", "-", "Panel heading."),
        ("subtitle", "string", "-", "Model or mode line, muted."),
        ("streaming", "boolean", "false", "Enables the caret and stop control."),
        ("className", "string", "-", "Merged last."),
    ],
    "editor": [
        ("title", "string", "-", "Document or file name."),
        ("subtitle", "string", "-", "Path or status, muted."),
        ("readOnly", "boolean", "false", "Removes the caret and edit affordances."),
        ("className", "string", "-", "Merged last."),
    ],
    "media": [
        ("title", "string", "-", "Media label."),
        ("subtitle", "string", "-", "Alt-derived caption or duration."),
        ("aspect", "string", '"16/9"', "Reserved box, so nothing shifts while loading."),
        ("className", "string", "-", "Merged last."),
    ],
    "commerce": [
        ("title", "string", "-", "Product or plan name."),
        ("subtitle", "string", "-", "Short differentiator, muted."),
        ("price", "number", "-", "Amount in the smallest sensible unit."),
        ("className", "string", "-", "Merged last."),
    ],
    "form": [
        ("title", "string", "-", "Form or step heading."),
        ("subtitle", "string", "-", "What happens after submit."),
        ("required", "boolean", "false", "Marks the field group as required."),
        ("className", "string", "-", "Merged last."),
    ],
    "layout": [
        ("title", "string", "-", "Region heading, often visually hidden."),
        ("subtitle", "string", "-", "Context line, muted."),
        ("sticky", "boolean", "false", "Enables the sticky behavior where the layout defines one."),
        ("className", "string", "-", "Merged last."),
    ],
    "devtool": [
        ("title", "string", "-", "Panel label."),
        ("subtitle", "string", "-", "Environment or build id, muted."),
        ("collapsed", "boolean", "false", "Summary-only rendering."),
        ("className", "string", "-", "Merged last."),
    ],
    "utility": [
        ("title", "string", "-", "Control label."),
        ("subtitle", "string", "-", "Hint, muted."),
        ("value", "string", "-", "Current value for controlled use."),
        ("className", "string", "-", "Merged last."),
    ],
    "mobile": [
        ("title", "string", "-", "Screen or sheet title."),
        ("subtitle", "string", "-", "Supporting line, muted."),
        ("safeArea", "boolean", "true", "Respects the notch and home indicator insets."),
        ("className", "string", "-", "Merged last."),
    ],
    "email": [
        ("title", "string", "-", "Email heading."),
        ("subtitle", "string", "-", "Preview text, muted."),
        ("width", "number", "600", "Table width, max 600 for deliverability."),
        ("className", "string", "-", "Merged last."),
    ],
    "print": [
        ("title", "string", "-", "Document title for the print header."),
        ("subtitle", "string", "-", "Revision or date line."),
        ("pageSize", '"A4" | "Letter"', '"A4"', "Applied through @page."),
        ("className", "string", "-", "Merged last."),
    ],
    "seo": [
        ("title", "string", "-", "Primary value, usually the H1 text."),
        ("subtitle", "string", "-", "Description, 150 to 160 characters."),
        ("structured", "boolean", "true", "Emits JSON-LD for the entity."),
        ("className", "string", "-", "Merged last."),
    ],
    "a11y": [
        ("title", "string", "-", "Visible label."),
        ("subtitle", "string", "-", "Instruction, muted."),
        ("live", '"polite" | "assertive" | "off"', '"polite"', "ARIA live politeness for announcements."),
        ("className", "string", "-", "Merged last."),
    ],
    "enterprise": [
        ("title", "string", "-", "Record or setting name."),
        ("subtitle", "string", "-", "Owner, scope or timestamp, muted."),
        ("restricted", "boolean", "false", "Renders the permission-gated variant."),
        ("className", "string", "-", "Merged last."),
    ],
}

# Motion contract printed on every page (spec 6.14: no zero-animation components).
MOTION: dict[str, str] = {
    "surface": "Hover lift of 2px over 240ms, or an 8px rise on first paint when it is the last element of a region.",
    "aurora": "Three blobs drift for 30 to 44s on transform only; frozen at 0 opacity change under reduced motion.",
    "motion": "Entrance fires once, 16px of travel, ease-out, and renders the final state instantly under reduced motion.",
    "section": "Header reveals with a 60ms cascade; the body is never staggered more than 400ms in total.",
    "divider": "Hairline fades from 0 to full opacity over 240ms when it enters the viewport.",
    "card": "4px rise and a one-step fill increase on hover, 240ms; the entrance is a 16px rise with 60ms cascade.",
    "button": "1px lift and a 0.98 press, 140ms; the icon travels 2px on hover and nothing animates on load.",
    "input": "Focus ring appears in 140ms, the label rises to the top border, and the error line slides in 8px.",
    "nav": "Interpolates to a condensed glass bar after 24px of scroll, 240ms; the active indicator slides.",
    "data": "Bars and lines draw once at 760ms when 40 percent visible; hover raises opacity, never position.",
    "table": "Rows tint over 120ms on hover; tables never stagger on entry, and bulk actions slide up 8px.",
    "chat": "Tokens appear as they stream, the caret blinks for 1s and stops 120ms after the stream ends.",
    "overlay": "Backdrop fades 180ms, surface rises 8px and scales from 0.98 over 240ms; exit is 160ms.",
    "feedback": "Shimmer travels at 1.4s linear; states cross-fade in 240ms and never flash.",
    "marketing": "Headline, lead and action stagger at 120ms intervals; one scroll-linked scene per page, maximum.",
    "shell": "Sidebar collapses over 240ms with a width and opacity pair; the content region never re-layouts twice.",
    "ai": "Reasoning drawer expands over 420ms via grid-template-rows; the caret signals waiting after 3s of stall.",
    "editor": "The find bar drops 8px over 240ms; comment threads expand with the same height technique as drawers.",
    "media": "Poster fades to video over 240ms after metadata; hover raises the controls without moving the frame.",
    "commerce": "Gallery cross-fades in 240ms; quantity steps use a 0.98 press; nothing bounces.",
    "form": "Step transitions slide 16px and fade in 240ms; validation messages appear at 8px with no shake.",
    "layout": "Sticky elements pin with a hairline that fades in over 240ms; regions do not animate on load.",
    "devtool": "Panels toggle in 240ms; the timeline scrubs with a 0.06s spring and never snaps past the cursor.",
    "utility": "Copy confirms with an inline icon swap in 140ms; tooltips delay 400ms and fade in 120ms.",
    "mobile": "Sheets rise 24px over 320ms with a soft spring; rows dim to 0.9 on press instead of scaling.",
    "email": "No motion is possible, so hierarchy carries the rhythm; the same layout is used in the web preview.",
    "print": "Transitions are suppressed; the reveal classes resolve to their final state before printing.",
    "seo": "No visible motion: the structured data must stay identical to the rendered content.",
    "a11y": "Announcements do not animate; the visible focus ring appears in 140ms and is never removed.",
    "enterprise": "Permission changes cross-fade in 240ms; audit rows enter with a 60ms cascade, capped at 400ms.",
}

# ASCII preview per kind, drawn with the actual box metrics of the component.
PREVIEW: dict[str, list[str]] = {
    "surface": [
        "+------------------------------------------+",
        "|  Surface            hairline 1px         |",
        "|                                          |",
        "|  fill      rgba glass     blur 18px      |",
        "|  highlight 1px inset top  gradient       |",
        "+------------------------------------------+",
        "   ^ above a background, never on flat fill",
    ],
    "aurora": [
        "  .-~-._            blobs, 30-44s drift",
        " (       )      .-~-.",
        "  `-.  .-'    (  2   )       3",
        "     `'         `-.-'",
        "  ground #06070c, grain 3.5%",
    ],
    "motion": [
        "  y 16px  -->  0px     opacity 0 --> 1",
        "  [=====>            ] 0.76s ease-out",
        "  fires once at 25% visibility",
    ],
    "section": [
        "+--------------------------------------------------+",
        "| OVERLINE                    quiet zone 96 to 128  |",
        "| Section title, 40px semibold                      |",
        "| One lead sentence, muted, max 62ch                |",
        "+--------------------------------------------------+",
        "|                    content                        |",
        "+--------------------------------------------------+",
    ],
    "divider": [
        "---------------------- Label ---------------------- ",
        "  hair soft, 1px, full bleed inside the container",
    ],
    "card": [
        "+------------------------------+",
        "| [icon]        ...            |",
        "| Glass card                   |",
        "| Supporting line, muted       |",
        "+------------------------------+",
        "  hover: -4px, fill +1 step, 240ms",
    ],
    "button": [
        "  +-------------------------+",
        "  |  [i]  Primary action    |   1px lift, 0.98 press",
        "  +-------------------------+",
        "    focus ring 2px, offset 2px, never removed",
    ],
    "input": [
        "  Label                                  helper",
        "  +------------------------------------+",
        "  | value                          |  v |",
        "  +------------------------------------+",
        "   error line appears 8px below, --danger",
    ],
    "nav": [
        "+--------------------------------------------------+",
        "| brand   Home  Product  Pricing   [ Sign in ]     |",
        "+--------------------------------------------------+",
        "  condenses to 56px + glass after 24px of scroll",
    ],
    "data": [
        "  94 |          .-.-.       draw once at 760ms",
        "  70 |     .-.-'     `-._",
        "  46 | .-.'              `-._     grid 8%",
        "  22 |'                      `-.   label --fg-muted",
        "     +--------------------------",
        "      Jan   Mar   May   Jul   Sep",
    ],
    "table": [
        "+----------+---------+--------+----------+",
        "| Name     | Status  |  MRR   | Updated  | <- sticky",
        "+----------+---------+--------+----------+",
        "| Acme     | Active  | 12,400 | 2 min    |",
        "| Northwind| Trial   |    900 | 1 h      |  hover 120ms",
        "+----------+---------+--------+----------+",
    ],
    "chat": [
        "  [sparkle] Model name            streaming  *",
        "  Answer as a 760px document, 16px / 1.7",
        "",
        "  +------------------------------------------+",
        "  | [code block]                             |",
        "  +------------------------------------------+",
        "  [copy] [retry] [thumbs]        actions row",
    ],
    "overlay": [
        "  +------------------------------------+",
        "  | Heading                     [ x ]  |   rise 8px + scale 0.98",
        "  | Body copy, one idea per line       |   backdrop blur 8px, 72%",
        "  |                    [Cancel] [Save] |",
        "  +------------------------------------+",
    ],
    "feedback": [
        "  ( ! )  Nothing here yet",
        "         One sentence of explanation.",
        "         [ Primary action ]",
        "  tone: info | warn | danger, 4.5:1 text contrast",
    ],
    "marketing": [
        "  OVERLINE",
        "  Headline that states the outcome        +------------------+",
        "  Lead, one sentence, max 62ch            |   product view   |",
        "  [ Primary ]  [ Secondary ]              |   glass, 2px pad |",
        "  trusted by [ l o g o s ]                +------------------+",
    ],
    "shell": [
        "+--------+-----------------------------------------+",
        "| brand  | Topbar: search, filters, account        |",
        "|--------|-----------------------------------------|",
        "| nav    |                                         |",
        "|  18/64 |  Content region, 24px gutter            |",
        "| auto   |                                         |",
        "+--------+-----------------------------------------+",
    ],
    "ai": [
        "  > Reasoning                 expand 420ms",
        "    1. parse the request",
        "    2. call the tool",
        "  --------------------------------------------",
        "  Answer, streaming ......... *",
    ],
    "editor": [
        "  12 | export function priceOf(qty: number) {",
        "  13 |   return qty * UNIT;",
        "  14 | }",
        "     linenos 40% opacity, 60ch measure, no wrap",
    ],
    "media": [
        "+------------------------------------+",
        "|                                    |",
        "|            play overlay            |   16/9 reserved box",
        "|                                    |   poster cross-fade 240ms",
        "+------------------------------------+",
    ],
    "commerce": [
        "  +--------------+  Plan name            $49/mo",
        "  |   product    |  One differentiator line",
        "  |   1:1 box    |  [ Choose plan ]",
        "  +--------------+  3 features, direct labels",
    ],
    "form": [
        "  1 Contact  --  2 Details  --  3 Confirm",
        "  +--------------------------------------+",
        "  | Label *                              |",
        "  | [ value                    ]         |",
        "  | 8px  error message, --danger         |",
        "  +--------------------------------------+",
        "                     [ Back ] [ Continue ]",
    ],
    "layout": [
        "+-------------------+------------------------------+",
        "| sticky rail       |  content, measure 62ch       |",
        "| 240px @ 1024px    |  gap 32px, gutter 24px       |",
        "+-------------------+------------------------------+",
        "  collapses to one column below 880px",
    ],
    "devtool": [
        "  [ 200 ] GET /api/usage       142ms   * collapse",
        "  [ 500 ] POST /api/chat       1.2s    * expand",
        "  ------------------------------------------------",
        "  timing bar: 3 steps, --fg-muted, tabular",
    ],
    "utility": [
        "  Copy  [icon]  ->  Copy  [check]   140ms swap",
        "  no toast, no layout shift, aria-live polite",
    ],
    "mobile": [
        "+---------------------+",
        "| 9:41      title     |   safe area respected",
        "|                     |",
        "|  cards, 16px gutter |",
        "+---------------------+",
        "     sheet, 320ms spring",
    ],
    "email": [
        "  +--------------------------------------+",
        "  | table 600px, inline styles           |",
        "  | H1 24px   body 16px/1.5              |",
        "  | [ 600x220 hero, hosted as an image ] |",
        "  | [ CTA, padded 16x32, one color ]     |",
        "  +--------------------------------------+",
    ],
    "print": [
        "  +--------------------------------------+",
        "  | Title                    page 1 / 4  |",
        "  | ----------------------------------  |",
        "  | black on white, 12pt, 1in margins    |",
        "  +--------------------------------------+",
    ],
    "seo": [
        "  <title>Primary value | Brand</title>",
        "  <meta name=\"description\" content=\"150-160 chars\" />",
        "  <link rel=\"canonical\" ... />",
        "  <script type=\"application/ld+json\"> { ... } </script>",
    ],
    "a11y": [
        "  [ Skip to content ]   visible on focus",
        "  aria-live=\"polite\"   status updates",
        "  focus ring 2px --accent, offset 2px",
    ],
    "enterprise": [
        "  +--------------------------------------------+",
        "  | Role            Members   Scope      Audit |",
        "  | Owner                 2   org        yes   |",
        "  | Billing admin         1   workspace  yes   |",
        "  +--------------------------------------------+",
        "  restricted rows render the gated variant",
    ],
}

# Usage example per kind. Component names and labels are injected per file.
EXAMPLE: dict[str, str] = {
    "surface": '<{X}>\n  <p className="text-[15px] text-[var(--fg)]">{T1}</p>\n  <p className="mt-2 text-[13px] text-[var(--fg-muted)]">{T2}</p>\n</{X}>',
    "aurora": '<{X} intensity={{0.6}} className="fixed inset-0 -z-10" />',
    "motion": '<{X} delay={{120}}>\n  <Surface>{T1}</Surface>\n</{X}>',
    "section": '<{X} title="{T1}" subtitle="{T2}" density="default">\n  <div className="grid gap-6 md:grid-cols-3">{c}</div>\n</{X}>',
    "divider": '<{X} label="{T1}" />',
    "card": '<{X} title="{T1}" subtitle="{T2}" interactive />',
    "button": '<{X} iconRight={{<ArrowRight className="size-4" />}} onClick={{save}}>\n  {T1}\n</{X}>',
    "input": '<{X} title="{T1}" subtitle="{T2}" value={{email}} onChange={{setEmail}} />',
    "nav": '<{X} title="{T1}" subtitle="{T2}" current="/{N}" />',
    "data": '<{X} title="{T1}" subtitle="{T2}" values={{[12, 18, 15, 24, 31, 28]}} />',
    "table": '<{X} title="{T1}" subtitle="{T2}" pageSize={{10}} />',
    "chat": '<{X} title="{T1}" subtitle="{T2}" streaming />',
    "overlay": '<{X} title="{T1}" subtitle="{T2}" open={{open}} onOpenChange={{setOpen}} />',
    "feedback": '<{X} title="{T1}" subtitle="{T2}" tone="info" onRetry={{retry}} />',
    "marketing": '<{X}\n  title="{T1}"\n  subtitle="{T2}"\n  action={{<ButtonPrimary>Start free</ButtonPrimary>}}\n/>',
    "shell": '<{X} title="{T1}" subtitle="{T2}">\n  {c}\n</{X}>',
    "ai": '<{X} title="{T1}" subtitle="{T2}" streaming={{false}} />',
    "editor": '<{X} title="{T1}" subtitle="{T2}" readOnly={{false}} />',
    "media": '<{X} title="{T1}" subtitle="{T2}" aspect="16/9" />',
    "commerce": '<{X} title="{T1}" subtitle="{T2}" price={{49}} />',
    "form": '<{X} title="{T1}" subtitle="{T2}" onSubmit={{submit}} />',
    "layout": '<{X} title="{T1}" subtitle="{T2}">\n  {c}\n</{X}>',
    "devtool": '<{X} title="{T1}" subtitle="{T2}" />',
    "utility": '<{X} title="{T1}" subtitle="{T2}" value={{value}} onValueChange={{setValue}} />',
    "mobile": '<{X} title="{T1}" subtitle="{T2}" safeArea />',
    "email": '<{X} title="{T1}" subtitle="{T2}" width={{600}} />',
    "print": '<{X} title="{T1}" subtitle="{T2}" pageSize="A4" />',
    "seo": '<{X} title="{T1}" subtitle="{T2}" structured={{true}} />',
    "a11y": '<{X} title="{T1}" subtitle="{T2}" live="polite" />',
    "enterprise": '<{X} title="{T1}" subtitle="{T2}" restricted={{false}} />',
}

# Realistic label pool per kind, cycled by index so five hundred pages read differently.
LABELS: dict[str, list[tuple[str, str]]] = {
    "surface": [("Quarterly revenue", "Updated 2h ago"), ("Deployment summary", "eu-central-1"), ("Storage usage", "412 GB of 1 TB")],
    "aurora": [("Aurora layer", "Marketing pages, intensity 1"), ("Aurora layer", "App surfaces, intensity 0.5")],
    "motion": [("Entrance", "Once, on first view"), ("Entrance", "Delay 120ms")],
    "section": [("How it works", "Three steps from import to insight"), ("Pricing", "One plan, no seat minimums"), ("Security", "SOC 2 Type II, audited annually")],
    "divider": [("Draft", "Unpublished"), ("Or", "Alternative path"), ("Archived", "Read only")],
    "card": [("Usage this month", "82 percent of the included quota"), ("Latest invoice", "Paid on the 4th"), ("Team capacity", "6 of 12 seats active")],
    "button": [("Export CSV", "Downloads the current view"), ("Invite teammate", "Sends one email"), ("Run pipeline", "Queues a job now")],
    "input": [("Work email", "We never share it"), ("Workspace URL", "Lowercase, no spaces"), ("API key", "Rotate every 90 days")],
    "nav": [("Acme", "Workspace"), ("Billing", "Settings"), ("Overview", "This month")],
    "data": [("Revenue by month", "Last 6 months, USD"), ("Requests per second", "p95, 24 hours"), ("Conversion", "Visits to trials")],
    "table": [("Invoices", "48 results"), ("Team members", "12 seats"), ("Incidents", "Last 90 days")],
    "chat": [("Answer", "Model: nova-3, 1.4s"), ("Tool call", "Search, 2 sources"), ("Summary", "Edited 4 min ago")],
    "overlay": [("Invite a teammate", "They receive an email in a moment"), ("Delete workspace", "This cannot be undone"), ("Choose a plan", "Change at any time")],
    "feedback": [("Nothing to show yet", "Connect a source to populate this view"), ("Search returned no results", "Try a shorter term"), ("Upload failed", "Retry, or use a smaller file")],
    "marketing": [("Ship the boring parts faster", "Themes, tables, settings and email, already designed"), ("Every screen already considered", "Nova Vitral keeps one visual grammar across the whole product"), ("From idea to interface in an afternoon", "Structure first, then light")],
    "shell": [("Acme Console", "Production"), ("Northwind", "Workspace"), ("Billing", "Team of 8")],
    "ai": [("Reasoning", "4 steps, 900ms"), ("Generated draft", "Grounded on 3 sources"), ("Model settings", "nova-3, temperature 0.2")],
    "editor": [("pricing.ts", "Modified 2 min ago"), ("README.md", "Preview"), ("invoice.pdf", "Read only")],
    "media": [("Product tour", "1:42, captions available"), ("Q3 all-hands", "Recording, 48 min"), ("Onboarding clip", "0:38, silent")],
    "commerce": [("Pro plan", "For teams up to 50", 49), ("Business plan", "SSO and audit log", 199), ("Starter plan", "Solo builders", 0)],
    "form": [("Create an account", "No credit card required"), ("Shipping details", "Delivered in 3 days"), ("Report an issue", "We reply within one business day")],
    "layout": [("Documentation", "Guides, references and recipes"), ("Changelog", "Released weekly"), ("Settings", "Workspace preferences")],
    "devtool": [("Network", "Production build"), ("Console", "2 warnings"), ("Timeline", "Session 4b21")],
    "utility": [("Copy link", "Copies to clipboard"), ("Time zone", "Stored per account"), ("Currency", "Display only")],
    "mobile": [("Orders", "Today"), ("Profile", "Signed in"), ("Notifications", "3 unread")],
    "email": [("Welcome to Acme", "Confirm your address to get started"), ("Your invoice is ready", "Payment received, thank you"), ("Weekly digest", "Five changes worth knowing")],
    "print": [("Statement of work", "Revision 3, 2026-09-15"), ("Usage report", "Billing period August 2026"), ("Handover checklist", "Project Meridian")],
    "seo": [("Nova Vitral pricing", "One plan, no seat minimums, cancel in one click"), ("Glass UI components", "Five hundred animated React components"), ("Changelog", "Every release since 1.0, written for humans")],
    "a11y": [("Skip to content", "Visible on focus"), ("Status region", "Announced politely"), ("Keyboard map", "Every action reachable without a mouse")],
    "enterprise": [("Access review", "Owner: Platform, due in 6 days"), ("Data residency", "EU only, pinned"), ("Approval policy", "Two approvers above 10k")],
}

# Spec sections each category implements, printed on the page and in the README.
USES: dict[str, str] = {
    "core": "1.3, 2, 3.2, 6.14",
    "motion": "3.9, 6.1 to 6.14",
    "buttons": "3.1, 6.3",
    "inputs": "3.3, 9.3",
    "cards": "3.2, 3.13",
    "navigation": "3.6, 3.15",
    "data": "3.5, 3.13, 7.5",
    "chat": "4.1 to 4.9",
    "overlays": "3.4, 6.7",
    "feedback": "3.12, 6.11",
    "marketing": "3.7, 5.1 to 5.9",
    "shell": "5.8, 3.6",
    "ai": "4.1 to 4.9, 6.14",
    "editors": "3.3, 6.6",
    "media": "3.11, 6.10",
    "commerce": "5.2, 3.1",
    "forms": "3.3, 5.3",
    "layout": "3.7, 3.8, 5.6",
    "devtools": "3.10, 6.7",
    "utilities": "3.14, 6.3",
    "mobile": "8.3, 6.12",
    "email": "8.4, 9.6",
    "print": "8.5, 9.6",
    "seo": "8.6, 9.4",
    "a11y": "9.1, 9.2, 9.3",
    "enterprise": "5.8, 3.5, 9.2",
}

# Data shapes each category expects, shown in the per-category README.
DATA_SHAPES: dict[str, str] = {
    "data": "`values: number[]` plus optional `labels: string[]` and `format?: (value: number) => string`.",
    "table": "`rows: T[]`, `columns: { key, header, align?, render }[]`, `rowKey: (row: T) => string`.",
    "chat": "`messages: { id, role, content, createdAt, status }[]`, where `status` is `sending | streaming | done | failed`.",
    "commerce": "`product: { id, name, price, currency, media }`, `plan: { id, name, price, interval, features }`.",
    "enterprise": "`records: T[]`, `roleMap: Record<string, Permission[]>`, `audit: { actor, action, at }[]`.",
    "ai": "`run: { id, model, prompt, steps, output, tokens, cost, latencyMs }`.",
    "media": "`asset: { id, kind, src, poster?, width, height, durationMs? }`.",
    "email": "`{ branding, headline, body, cta, unsubscribeUrl }` as plain serializable data.",
}

# Anti-patterns printed per category, extending spec 9.5 with category-specific ones.
ANTI_PATTERNS: dict[str, list[str]] = {
    "core": [
        "Glass on a flat dark fill: without an aurora, gradient or image behind it, blur reads as gray fog.",
        "More than two stacked blur layers per region; each one costs compositing work and dulls the text.",
        "Removing the hairline because the surface already has a shadow. They do different jobs.",
    ],
    "motion": [
        "Entrances longer than 900ms, or travel above 24px on desktop.",
        "Animating layout properties (top, height, margin) instead of transform and opacity.",
        "A second scroll-linked scene on the same page as an existing one.",
    ],
    "buttons": [
        "Two solid primary buttons in one viewport.",
        "A purple or two-hue gradient fill. The system uses a single indigo ramp.",
        "Removing the focus ring to make hover look cleaner.",
    ],
    "inputs": [
        "Placeholder text used as the only label.",
        "Error messages that only change the border color.",
        "Autofocus on mobile, which raises the keyboard over the content.",
    ],
    "cards": [
        "Five equally weighted cards in a row: pick a hierarchy or use a table.",
        "Hover lift on non-interactive cards.",
        "An icon tile with three different accent colors in one grid.",
    ],
    "navigation": [
        "A menu that opens on hover only: keyboard users cannot reach it.",
        "Breadcrumbs past four levels instead of a section hub.",
        "A mobile sheet without scroll lock, so the page scrolls behind it.",
    ],
    "data": [
        "Pie charts with more than three slices; use bars instead.",
        "Legends that repeat the axis labels.",
        "Zero baselines removed from bar charts.",
    ],
    "table": [
        "Right-aligned text columns or left-aligned numbers.",
        "A skeleton that does not match the final row height, so the table jumps.",
        "Bulk actions that live only in a dropdown.",
    ],
    "chat": [
        "Assistant answers inside bubbles: they are documents, not messages.",
        "Auto-scroll that fights the reader when they scroll up.",
        "A stop control that appears only after the first token.",
    ],
    "overlays": [
        "Nested modals. Use a page or a sheet instead.",
        "Destructive confirmation without the object name in the copy.",
        "Closing on backdrop click for anything that loses data.",
    ],
    "feedback": [
        "Red used for non-destructive states.",
        "Exclamation marks and blame in error copy.",
        "Skeletons that persist longer than the real response time.",
    ],
    "marketing": [
        "Three accent colors in the hero.",
        "Feature grids of six equal tiles with no hierarchy.",
        "Gradient text outside the hero headline.",
    ],
    "shell": [
        "Two navigation systems visible at once.",
        "Sidebar sections without counts or states.",
        "Hiding navigation behind an avatar menu.",
    ],
    "ai": [
        "Reasoning shown by default with no collapse control.",
        "Token and cost metrics in the primary flow.",
        "Streaming text that reflows the whole page on every token.",
    ],
    "editors": [
        "Line numbers at full contrast, competing with the code.",
        "A toolbar with more than eight buttons.",
        "Comment threads that open in a modal.",
    ],
    "media": [
        "Auto-playing video with sound.",
        "Media without a reserved box, causing layout shift.",
        "Controls hidden on touch devices.",
    ],
    "commerce": [
        "Price hidden until the final step.",
        "Comparison tables with more than five columns.",
        "Stock urgency copy that changes on refresh.",
    ],
    "forms": [
        "Validation on first keystroke.",
        "More than seven fields without grouping.",
        "A disabled submit button with no explanation of what is missing.",
    ],
    "layout": [
        "Sticky rails taller than the viewport.",
        "Full-bleed bands used twice in a row.",
        "Measure above 80 characters.",
    ],
    "devtools": [
        "Color-coded log levels without a text label.",
        "Timeline panning that fights the page scroll.",
        "Raw stack traces as the first line of an error.",
    ],
    "utilities": [
        "Toasts for actions that already have inline confirmation.",
        "Tooltips as the only source of an action name.",
        "Destructive utilities placed next to copy actions.",
    ],
    "mobile": [
        "Touch targets below 44px.",
        "Sheets that cover the primary action.",
        "Landscape layouts designed after portrait, instead of together.",
    ],
    "email": [
        "Background images carrying meaning: many clients strip them.",
        "More than one CTA per email.",
        "Dark mode assumed to work without testing.",
    ],
    "print": [
        "Screenshots of tables instead of real tables.",
        "Color as the only carrier of meaning.",
        "Headers that repeat on every page with stale data.",
    ],
    "seo": [
        "Structured data that does not match the rendered content.",
        "Descriptions truncated mid-sentence.",
        "The same title on more than one route.",
    ],
    "a11y": [
        "aria-label duplicating visible text.",
        "Focus traps without an escape route.",
        "Motion that ignores prefers-reduced-motion.",
    ],
    "enterprise": [
        "Permissions explained only in documentation.",
        "Audit rows without an actor.",
        "Role names that do not match the customer's words.",
    ],
}
